### ISSUE TITLE
[BUG] Drone on mini map is not accurate

### ISSUE THREAD

**Issue by faithfaf** [Eagle-Enterprises/Training-Environment#27]
**Describe the bug**
The mini map drone does not match up to where the playable drone is in the level.

**To Reproduce**

1. Open blocks
2. Fly normally
3. Fly to baseball pitch as clear indicator of where I am in the world
4. Check mini map to see if mini map drone matches

**Expected behavior**
Drone on the mini map shows where I am in the world

**Screenshots**
![Capture Screenshot mini map bug](https://github.com/Eagle-Enterprises/Training-Environment/assets/161363231/d66605a5-a71f-4ad0-8ccd-68652b8cff5a)

**Desktop (please complete the following information):**

- OS: Windows 11

- Browser: Chrome

- Version  Unreal 4.2.7

**Additional context**

**Comment by maplebeans1** [comment]
Updated minimap mechanics to use a live camera view.
