### ISSUE TITLE
[BUG] Drone unable to pick up asset. 

### ISSUE THREAD

**Issue by yottabyte28** [Eagle-Enterprises/Training-Environment#42]
**Describe the bug**
A bug was discovered when trying to pick up any asset on the ballfield. Referencing older demo videos, this capability was solved but there is a new issue that is not letting the drone pick up any asset. 

**To Reproduce**

1. Using a controller fly the drone. 
2. Navigate over an asset
3. Press the "Y" button to grab the asset. 
4. Verify there is a red line that signals the asset is below the drone and it is able to be picked up. 

**Expected behavior**
After pressing the "Y" button the drone should pick up the asset. You should be able to fly the drone with the asset secured.

**Comment by maplebeans1** [comment]
Works - not broken
